### ISSUE TITLE
failed to perform "Exists" on destination, since Version 2.1.5

### ISSUE THREAD

**Issue by uhgtg** [bitnami-labs/charts-syncer#279]
### What steps will reproduce the bug?

Since the 2.1.5 release, we cannot sync our charts anymore with the exact same config then in the Version 2.1.3.
The error occurs with all our charts if they have a chart to sync. If the chart is already sync in our registry, the error does not occur 

### What do you see instead?

          ✘  Failed to push Helm chart: failed to perform "Exists" on destination: HEAD "https://registry.gitlab.my-registry.com/v2/charts-syncer/my-chart/manifests/sha256: ...": response status code 400: Bad Request
       ✘  unable to upload "my-chart-1.2.3" chart: Failed to push Helm chart: failed to perform "Exists" on destination: HEAD "https://registry.gitlab.my-registry.com/v2/charts-syncer/my-chart/manifests/sha256: ...": response status code 400: Bad Request
      github.com/bitnami/charts-syncer/pkg/client/target/common.(*Target).Unwrap:84:

**Comment by tompizmor** [comment]
Hi @uhgtg! Do you mind sharing your config file (masking all sensitive information). I am interested on the source and target repositories Kind as well as any other configuration option you may have set up there.

**Comment by Sebastian-Materna** [comment]
I'm facing the same issue. For example this is the used config:
```yaml
source:
  repo:
    kind: HELM
    url: https://charts.jetstack.io
    disableChartsIndex: true
target:
  repo:
    kind: OCI
    url: oci://xxx.azurecr.io/helm/synced
skipImages: true
charts:
  - cert-manager
```

Error:
```
Running charts-syncer for config: sync-config.jetstack.yaml
 »  Syncing charts
    ✔  Chart list loaded
    ✔  There is 1 chart out of sync!
    »  ==> Syncing "cert-manager-1.19.1" chart (1/1)
       »  Wrapping Helm chart "/home/xxx/.charts-syncer/f6820ec5adb6d665e1401f80acb6f9812c57ab9c/cert-manager-1.19.1.tgz"
          ✔  Helm chart uncompressed to "/tmp/charts-syncer3223807896/charts-syncer851704070/dt-wrap3667500031"
          ✔  Images.lock file written to "/tmp/charts-syncer3223807896/charts-syncer851704070/wrap/chart/Images.lock"
          ✔  Compressed into "/tmp/charts-syncer3223807896/wraps/cert-manager-1.19.1.wrap.tgz"
       »  Unwrapping Helm chart "/tmp/charts-syncer3223807896/wraps/cert-manager-1.19.1.wrap.tgz"
          ✔  Helm chart uncompressed to "/tmp/charts-syncer3223807896/charts-syncer577028322/dt-wrap959795189"
          ✔  Helm chart relocated successfully
          ⚠️  The bundle does not include any image
          ✘  Failed to push Helm chart: failed to perform "Exists" on destination: HEAD "https://xxx.azurecr.io/v2/helm/synced/cert-manager/manifests/sha256:c3a68cb0b771e136a95d0a5d9bfdf1190e82a5a858bf6a03aac8d8a8bacbd921": response status code 400: Bad Request
       ✘  unable to upload "cert-manager-1.19.1" chart: Failed to push Helm chart: failed to perform "Exists" on destination: HEAD "https://xxx.azurecr.io/v2/helm/synced/cert-manager/manifests/sha256:c3a68cb0b771e136a95d0a5d9bfdf1190e82a5a858bf6a03aac8d8a8bacbd921": response status code 400: Bad Request
      github.com/bitnami/charts-syncer/pkg/client/target/common.(*Target).Unwrap:84:
    ⚠️  Failed syncing "cert-manager-1.19.1" chart: Failed to push Helm chart: failed to perform "Exists" on destination: HEAD "https://xxx.azurecr.io/v2/helm/synced/cert-manager/manifests/sha256:c3a68cb0b771e136a95d0a5d9bfdf1190e82a5a858bf6a03aac8d8a8bacbd921": response status code 400: Bad Request
    ✘  Error syncing charts: Failed to push Helm chart: failed to perform "Exists" on destination: HEAD "https://xxx.azurecr.io/v2/helm/synced/cert-manager/manifests/sha256:c3a68cb0b771e136a95d0a5d9bfdf1190e82a5a858bf6a03aac8d8a8bacbd921": response status code 400: Bad Request
Error: Error syncing charts: Failed to push Helm chart: failed to perform "Exists" on destination: HEAD "https://xxx.azurecr.io/v2/helm/synced/cert-manager/manifests/sha256:c3a68cb0b771e136a95d0a5d9bfdf1190e82a5a858bf6a03aac8d8a8bacbd921": response status code 400: Bad Request
```
The version of the chart is already in our container registry, but this should not crash charts-syncer. Also authentication is handled via environment variables.
This issue exists since `2.1.4`.

**Comment by tompizmor** [comment]
Hi @uhgtg, @Sebastian-Materna, I track the issue to a helm dependency version update in the 2.1.4 release. The change at https://github.com/bitnami/charts-syncer/pull/286 should fix it. I will let you know once I release a new version.

**Comment by tompizmor** [comment]
@uhgtg @Sebastian-Materna I just released a new version of charts-syncer ([v2.1.6](https://github.com/bitnami/charts-syncer/releases/tag/v2.1.6))

**Comment by Sebastian-Materna** [comment]
Hi @tompizmor thanks for the quick work. I've already tested this but it's still failing (not cert-manager but openfga):
```yaml
source:
  repo:
    kind: HELM
    url: https://openfga.github.io/helm-charts
    disableChartsIndex: true
target:
  repo:
    kind: OCI
    url: https://xxx.azurecr.io/helm/synced
skipImages: true
charts:
  - openfga
```

error:
```bash
Running charts-syncer for config: sync-config.openfga.yaml
 »  Syncing charts
    ✔  Chart list loaded
    ✔  There is 1 chart out of sync!
    »  ==> Syncing "openfga-0.2.45" chart (1/1)
       »  Wrapping Helm chart "/home/user/.charts-syncer/d619b1f2bd51f546c003ad802bc428c618a435a5/openfga-0.2.45.tgz"
          ✔  Helm chart uncompressed to "/tmp/charts-syncer786244035/charts-syncer3744571568/dt-wrap16670842"
          ✔  Images.lock file written to "/tmp/charts-syncer786244035/charts-syncer3744571568/wrap/chart/Images.lock"
          ✔  Compressed into "/tmp/charts-syncer786244035/wraps/openfga-0.2.45.wrap.tgz"
       »  Unwrapping Helm chart "/tmp/charts-syncer786244035/wraps/openfga-0.2.45.wrap.tgz"
          ✔  Helm chart uncompressed to "/tmp/charts-syncer786244035/charts-syncer3532765318/dt-wrap3054346617"
          ✔  Helm chart relocated successfully
          ✘  Failed to push Helm chart: failed to perform "Exists" on destination: HEAD "https://xxx.azurecr.io/v2/helm/synced/openfga/manifests/sha256:6a6707f9c7de0140b86e3a2d013c62e80a431f5e9411b38e08431e58d0acebc1": response status code 400: Bad Request
       ✘  unable to upload "openfga-0.2.45" chart: Failed to push Helm chart: failed to perform "Exists" on destination: HEAD "https://xxx.azurecr.io/v2/helm/synced/openfga/manifests/sha256:6a6707f9c7de0140b86e3a2d013c62e80a431f5e9411b38e08431e58d0acebc1": response status code 400: Bad Request
      github.com/bitnami/charts-syncer/pkg/client/target/common.(*Target).Unwrap:84:
    ⚠️  Failed syncing "openfga-0.2.45" chart: Failed to push Helm chart: failed to perform "Exists" on destination: HEAD "https://xxx.azurecr.io/v2/helm/synced/openfga/manifests/sha256:6a6707f9c7de0140b86e3a2d013c62e80a431f5e9411b38e08431e58d0acebc1": response status code 400: Bad Request
    ✘  Error syncing charts: Failed to push Helm chart: failed to perform "Exists" on destination: HEAD "https://xxx.azurecr.io/v2/helm/synced/openfga/manifests/sha256:6a6707f9c7de0140b86e3a2d013c62e80a431f5e9411b38e08431e58d0acebc1": response status code 400: Bad Request
Error: Error syncing charts: Failed to push Helm chart: failed to perform "Exists" on destination: HEAD "https://xxx.azurecr.io/v2/helm/synced/openfga/manifests/sha256:6a6707f9c7de0140b86e3a2d013c62e80a431f5e9411b38e08431e58d0acebc1": response status code 400: Bad Request
```
I'm using the latest version `2.1.6`

**Comment by uhgtg** [comment]
Hey
thanks for the quick answers, I was out of office, so sorry for the late answer

As @Sebastian-Materna already said does the error still occur in the version 2.1.6, in my case eg for the chart external-dns:

```yaml
---
source:
  repo:
    kind: HELM
    url: https://kubernetes-sigs.github.io/external-dns
target:
  repo:
    kind: OCI
    url: https://registry.gitlab.my-registry.com/charts-syncer/helm-mirror
    auth:
      username: gitlab-ci-token
      password: my-token
charts:
  - external-dns
skipImages: true
```

```
 »  Syncing charts
    ✔  Chart list loaded
    ✔  There is 1 chart out of sync!
    »  ==> Syncing "external-dns-1.19.0" chart (1/1)
       »  Wrapping Helm chart "/.charts-syncer/cb1cd70546f4c5de6fe8c820d26a62094152c3d0/external-dns-1.19.0.tgz"
          ✔  Helm chart uncompressed to "/tmp/charts-syncer182397155/charts-syncer3067285988/dt-wrap4016343621"
          ✔  Images.lock file written to "/tmp/charts-syncer182397155/charts-syncer3067285988/wrap/chart/Images.lock"
          ✔  Compressed into "/tmp/charts-syncer182397155/wraps/external-dns-1.19.0.wrap.tgz"
       »  Unwrapping Helm chart "/tmp/charts-syncer182397155/wraps/external-dns-1.19.0.wrap.tgz"
          ✔  Helm chart uncompressed to "/tmp/charts-syncer182397155/charts-syncer1527191726/dt-wrap1124409798"
          ✔  Helm chart relocated successfully                                  rap1124409798/chart" with prefix "registry.gitlab.my-registry.com/charts-syncer/helm-mirror" (0s)
          ⚠️  The bundle does not include any image
          ✘  Failed to push Helm chart: failed to perform "Exists" on destination: HEAD "https://registry.gitlab.my-registry.com/v2/charts-syncer/external-dns/manifests/sha256:943de054a679c874ea50abfba51f20f6316cf5f6fe4dbab6666e53e3b292839b": response status code 400: Bad Request
       ✘  unable to upload "external-dns-1.19.0" chart: Failed to push Helm chart: failed to perform "Exists" on destination: HEAD "https://registry.gitlab.my-registry.com/v2/charts-syncer/external-dns/manifests/sha256:943de054a679c874ea50abfba51f20f6316cf5f6fe4dbab6666e53e3b292839b": response status code 400: Bad Request
      github.com/bitnami/charts-syncer/pkg/client/target/common.(*Target).Unwrap:84:
    ⚠️  Failed syncing "external-dns-1.19.0" chart: Failed to push Helm chart: failed to perform "Exists" on destination: HEAD "https://registry.gitlab.my-registry.com/v2/charts-syncer/external-dns/manifests/sha256:943de054a679c874ea50abfba51f20f6316cf5f6fe4dbab6666e53e3b292839b": response status code 400: Bad Request
Error: Error syncing charts: Failed to push Helm chart: failed to perform "Exists" on destination: HEAD "https://registry.gitlab.my-registry.com/v2/charts-syncer/external-dns/manifests/sha256:943de054a679c874ea50abfba51f20f6316cf5f6fe4dbab6666e53e3b292839b": response status code 400: Bad Request
    ✘  Error syncing charts: Failed to push Helm chart: failed to perform "Exists" on destination: HEAD "https://registry.gitlab.my-registry.com/v2/charts-syncer/external-dns/manifests/sha256:943de054a679c874ea50abfba51f20f6316cf5f6fe4dbab6666e53e3b292839b": response status code 400: Bad Request
```

The exact same config does work perfectly in version 2.1.3

**Comment by tompizmor** [comment]
Hi @uhgtg @Sebastian-Materna, I am afraid I can't reproduce this issue no matter which kind of target registry I use. Could you please share more details about your execution environment? In which operating system are you running the tool?

**Comment by Sebastian-Materna** [comment]
HI @tompizmor,
Locally using WSL2 with kernel `Linux XXX 6.6.87.2-microsoft-standard-WSL2 #1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:30:46 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux`. In our CI/CD also linux (Ubuntu 22.04) is used. Also tried on Windows with the same result.

**Comment by uhgtg** [comment]
Hi
locally I use macOS 15.7.2 (24G325) I run the charts-syncer with 
`docker run --rm -v "$(pwd):/data" --name charts-syncer bitnami/charts-syncer:2.1.6 sync --latest-version-only -c /data/charts/cert-manager.yaml`
In the CI we use [v18.4.4-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v18.4.4-ee)

**Comment by tompizmor** [comment]
@Sebastian-Materna @uhgtg can you try with the new 2.1.7 version? 

https://github.com/bitnami/charts-syncer/releases/tag/v2.1.7

**Comment by Sebastian-Materna** [comment]
Hi @tompizmor thank you for the updated version. This works with all of my configurations 👍 .

**Comment by uhgtg** [comment]
Yes the new version also works for me. Thanks for your help.

**Comment by tompizmor** [comment]
Nice! Closing the issue!
